spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://configserver:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Flashstack Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      flashstack:
        gatewayserver: DEBUG