server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8071"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true