server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "configserver:http://configserver:8071"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Flashstack Loans Application"
    version: "1.0.0"

logging:
  level:
    com:
      flashstack:
        loans: DEBUG