server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to flashstack accounts related local APIs"
  contactDetails:
    name: "John Doe"
    email: "john@flashstack.com"
  onCallSupport:
    - (+91) 1234567890
    - (+91) 1234567891